Мария, привет!

Спасибо за комментарии. 

С точки зрения логики здесь нет противоречия, указанная ветвь отрабатывает только после создания таблиц в первой ветке (см. скриншот https://github.com/agredyaev/de-project-3).

Возможно необходимо создать подключение к Posgres c id = 'postgresql_de' и тогда ошибка пропадёт.

