Мария, привет!

Спасибо за комментарии. 

С точки зрения логики здесь нет противоречия, указанная ветвь отрабатывает только после создания таблиц в первой ветке (см. скрин).

Возможно необходимо создать подключение к Posgres c id = 'postgresql_de' и тогда ошибка пропадёт.

